name: Build and deploy
on:
  push:
    paths:
      - 'public/**'

env:
  # Image & ACR  
  ACR_NAME: "pierrcacr"
  IMAGE_NAME: "stats-rugby-app-service"
  IMAGE_VERSION: "0.1.7"
  RG_ACR_Name: "RG-BE-ACR"

  # WebApp
  SITE_NAME: "stats-rugby-as" 

jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2  

    - name: Login Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "localhost:5500"
        replace: "${{ env.SITE_NAME }}.azurewebsites.net"

    - name: Connexion à Azure Container Registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_NAME }}
        password: "${{ secrets.ACR_KEY }}"

    - name: Extraire les métadonnées docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }} 
        tags: |
         type=semver,pattern={{version}},value=${{ env.IMAGE_VERSION }}

    - name: Construire et pousser image Docker
      uses: docker/build-push-action@v3.1.0
      with:         
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}