name: Create DB
on:
  workflow_dispatch

env:
  RG_NAME_DB: "RG-DB"
  LOCATION: "westeurope"
  SERVER_NAME: "statrugby"

jobs:

  Build_Image:
    runs-on: ubuntu-latest

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2  

    - name: Login Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

