name: Deploy MySQL
on:
  workflow_dispatch

env:
  RG_NAME_DB: "RG-DB"
  LOCATION: "westeurope"
  SERVER_NAME: "statrugby"


jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2  

    - name: Login Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - uses: azure/mysql@v1
      with:
        server-name: statrugby.mysql.database.azure.com
        username: pierrc@statrugby
        password: Satanas@007
        # This is optional, you want to connect directly
        database: REPLACE_WITH_DATABASE_NAME
        sql-file: './MySQL/create_base.sql'        