name: Deploy MySQL
on:
  workflow_dispatch

env:
  RG_NAME_DB: "RG-DB"
  LOCATION: "westeurope"
  SERVER_NAME: "statrugby"

jobs:

  Build_Image:
    runs-on: ubuntu-20.04

    steps:

    - name: Recuperation du repos 
      uses: actions/checkout@v2  

    - name: Login Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Az CLI
      run: |
        az group create \
          --name ${{ env.RG_NAME_DB }} \
          --location ${{ env.LOCATION }}
        
        az mysql server create \
          --resource-group ${{ env.RG_NAME_DB }} \
          --name ${{ env.SERVER_NAME }} \
          --location ${{ env.LOCATION }} \
          --admin-user ${{ secrets.DB_USER}} \
          --admin-password ${{ secrets.DB_PASS}} \
          --sku-name GP_Gen5_2
        
        az mysql server firewall-rule create \
          --resource-group ${{ env.RG_NAME_DB }} \
          --server-name ${{ env.SERVER_NAME }} \
          --name Allow-All \
          --start-ip-address 0.0.0.0 \
          --end-ip-address 255.255.255.255

        az mysql server update \
          --resource-group ${{ env.RG_NAME_DB }} \
          --name ${{ env.SERVER_NAME }} \
          --ssl-enforcement Disabled

  
          
